// Local Database

export const lawyers = [
  {
    "lawyer_name": "Amit Sharma",
    "vidhik_id": "V123456",
    "lawyer_password": "amit123",
    "bar_council_no": "BCN123",
    "email": "amit.sharma@example.com",
    "photo_url": "https://images.app.goo.gl/GFHRkXec7FBceS6P9",
    "phone_no": "1234567890",
    "aadhar_no": "123456789012",
    "gender": "Male",
    "avg_price_range_per_hearing": [100, 300],
    "no_of_past_cases_fought": 50,
    "no_of_past_cases_won": 30,
    "rating": 4,
    "speciality": ["Criminal Defense", "Family Law"],
    "practicing_court": ["Supreme Court", "High Court"],
    "lawyer_location": "Cityville",
    "languages_known": ["English", "Spanish"],
    "experience_in_years": 10,
    "endorsements": ["Entity123"],
    "cases_involved": ["Case123", "Case456"],
    "lawyer_type": ["Advocate"],
    "additional_ids": ["AIBE123", "OS456", "ST789", "StateName"]
  },
  {
    "lawyer_name": "Priya Verma",
    "vidhik_id": "V654321",
    "lawyer_password": "priya456",
    "bar_council_no": "BCN456",
    "email": "priya.verma@example.com",
    "photo_url": "https://images.app.goo.gl/RxgGPFysUwAawqrJ6",
    "phone_no": "9876543210",
    "aadhar_no": "987654321098",
    "gender": "Female",
    "avg_price_range_per_hearing": [200, 400],
    "no_of_past_cases_fought": 40,
    "no_of_past_cases_won": 25,
    "rating": 4,
    "speciality": ["Corporate Law", "Intellectual Property"],
    "practicing_court": ["District Court", "Family Court"],
    "lawyer_location": "Towntown",
    "languages_known": ["English", "French"],
    "experience_in_years": 8,
    "endorsements": ["Entity456"],
    "cases_involved": ["Case789", "Case012"],
    "lawyer_type": ["Advocate", "Consultant"],
    "additional_ids": ["AIBE456", "OS789", "ST012", "StateName"]
  },
  {
    "lawyer_name": "Rahul Kapoor",
    "vidhik_id": "V789012",
    "lawyer_password": "rahul789",
    "bar_council_no": "BCN789",
    "email": "rahul.kapoor@example.com",
    "photo_url": "https://example.com/rahulkapoor.jpg",
    "phone_no": "8765432109",
    "aadhar_no": "876543210987",
    "gender": "Male",
    "avg_price_range_per_hearing": [150, 350],
    "no_of_past_cases_fought": 35,
    "no_of_past_cases_won": 20,
    "rating": 4,
    "speciality": ["Real Estate Law", "Immigration Law"],
    "practicing_court": ["High Court", "City Court"],
    "lawyer_location": "Villageton",
    "languages_known": ["English", "Mandarin"],
    "experience_in_years": 12,
    "endorsements": ["Entity789"],
    "cases_involved": ["Case345", "Case678"],
    "lawyer_type": ["Solicitor"],
    "additional_ids": ["AIBE789", "OS012", "ST345", "StateName"]
  },
  {
    "lawyer_name": "Neha Gupta",
    "vidhik_id": "V345678",
    "lawyer_password": "neha345",
    "bar_council_no": "BCN345",
    "email": "neha.gupta@example.com",
    "photo_url": "https://example.com/neha-gupta.jpg",
    "phone_no": "7654321098",
    "aadhar_no": "765432109876",
    "gender": "Female",
    "avg_price_range_per_hearing": [120, 300],
    "no_of_past_cases_fought": 25,
    "no_of_past_cases_won": 15,
    "rating": 4,
    "speciality": ["Family Law", "Labor Law"],
    "practicing_court": ["City Court", "District Court"],
    "lawyer_location": "Suburbia",
    "languages_known": ["English", "German"],
    "experience_in_years": 15,
    "endorsements": ["Entity345"],
    "cases_involved": ["Case234", "Case567"],
    "lawyer_type": ["Advocate", "Mediator"],
    "additional_ids": ["AIBE345", "OS678", "ST901", "StateName"]
  },
  {
    "lawyer_name": "Ankit Malhotra",
    "vidhik_id": "V567890",
    "lawyer_password": "ankit567",
    "bar_council_no": "BCN567",
    "email": "ankit.malhotra@example.com",
    "photo_url": "https://example.com/ankitmalhotra.jpg",
    "phone_no": "6543210987",
    "aadhar_no": "654321098765",
    "gender": "Male",
    "avg_price_range_per_hearing": [180, 400],
    "no_of_past_cases_fought": 28,
    "no_of_past_cases_won": 18,
    "rating": 4,
    "speciality": ["Criminal", "Tax Law"],
    "practicing_court": ["Supreme Court", "County Court"],
    "lawyer_location": "Townsville",
    "languages_known": ["English", "Spanish"],
    "experience_in_years": 10,
    "endorsements": ["Entity567"],
    "cases_involved": ["Case890", "Case123"],
    "lawyer_type": ["Advocate", "Consultant"],
    "additional_ids": ["AIBE567", "OS890", "ST123", "StateName"]
  },
  {
    "lawyer_name": "Pooja Desai",
    "vidhik_id": "V234567",
    "lawyer_password": "pooja234",
    "bar_council_no": "BCN234",
    "email": "pooja.desai@example.com",
    "photo_url": "https://example.com/poojadesai.jpg",
    "phone_no": "9876543210",
    "aadhar_no": "987654321098",
    "gender": "Female",
    "avg_price_range_per_hearing": [150, 300],
    "no_of_past_cases_fought": 45,
    "no_of_past_cases_won": 25,
    "rating": 4,
    "speciality": ["Civil Law", "Property Law"],
    "practicing_court": ["District Court", "High Court"],
    "lawyer_location": "Metroville",
    "languages_known": ["English", "Hindi"],
    "experience_in_years": 11,
    "endorsements": ["Entity234"],
    "cases_involved": ["Case678", "Case901"],
    "lawyer_type": ["Advocate", "Legal Advisor"],
    "additional_ids": ["AIBE234", "OS567", "ST890", "StateName"]
  },
  {
    "lawyer_name": "Rajeev Kapoor",
    "vidhik_id": "V678901",
    "lawyer_password": "rajeev678",
    "bar_council_no": "BCN678",
    "email": "rajeev.kapoor@example.com",
    "photo_url": "https://example.com/rajeevkapoor.jpg",
    "phone_no": "8765432109",
    "aadhar_no": "876543210987",
    "gender": "Male",
    "avg_price_range_per_hearing": [120, 350],
    "no_of_past_cases_fought": 30,
    "no_of_past_cases_won": 20,
    "rating": 4,
    "speciality": ["Family Law", "Consumer Law"],
    "practicing_court": ["High Court", "City Court"],
    "lawyer_location": "Township",
    "languages_known": ["English", "Punjabi"],
    "experience_in_years": 13,
    "endorsements": ["Entity678"],
    "cases_involved": ["Case234", "Case567"],
    "lawyer_type": ["Advocate", "Arbitrator"],
    "additional_ids": ["AIBE678", "OS901", "ST234", "StateName"]
  },
  {
    "lawyer_name": "Deepika Shah",
    "vidhik_id": "V890123",
    "lawyer_password": "deepika890",
    "bar_council_no": "BCN890",
    "email": "deepika.shah@example.com",
    "photo_url": "https://example.com/deepikashah.jpg",
    "phone_no": "7654321098",
    "aadhar_no": "765432109876",
    "gender": "Female",
    "avg_price_range_per_hearing": [130, 320],
    "no_of_past_cases_fought": 28,
    "no_of_past_cases_won": 18,
    "rating": 4,
    "speciality": ["Criminal Defense", "Corporate Law"],
    "practicing_court": ["Supreme Court", "District Court"],
    "lawyer_location": "Suburbia",
    "languages_known": ["English", "Gujarati"],
    "experience_in_years": 12,
    "endorsements": ["Entity890"],
    "cases_involved": ["Case123", "Case456"],
    "lawyer_type": ["Advocate", "Legal Consultant"],
    "additional_ids": ["AIBE890", "OS123", "ST456", "StateName"]
  },
  {
    "lawyer_name": "Sanjay Mehta",
    "vidhik_id": "V012345",
    "lawyer_password": "sanjay012",
    "bar_council_no": "BCN012",
    "email": "sanjay.mehta@example.com",
    "photo_url": "https://example.com/sanjaymehta.jpg",
    "phone_no": "6543210987",
    "aadhar_no": "654321098765",
    "gender": "Male",
    "avg_price_range_per_hearing": [180, 400],
    "no_of_past_cases_fought": 35,
    "no_of_past_cases_won": 25,
    "rating": 4,
    "speciality": ["Real Estate Law", "Immigration Law"],
    "practicing_court": ["High Court", "City Court"],
    "lawyer_location": "Metropolis",
    "languages_known": ["English", "Hindi"],
    "experience_in_years": 10,
    "endorsements": ["Entity012"],
    "cases_involved": ["Case567", "Case890"],
    "lawyer_type": ["Solicitor"],
    "additional_ids": ["AIBE012", "OS345", "ST678", "StateName"]
  },
  {
    "lawyer_name": "Shalini Reddy",
    "vidhik_id": "V345678",
    "lawyer_password": "shalini345",
    "bar_council_no": "BCN345",
    "email": "shalini.reddy@example.com",
    "photo_url": "https://example.com/shalinireddy.jpg",
    "phone_no": "9876543210",
    "aadhar_no": "987654321098",
    "gender": "Female",
    "avg_price_range_per_hearing": [200, 350],
    "no_of_past_cases_fought": 40,
    "no_of_past_cases_won": 30,
    "rating": 4,
    "speciality": ["Family Law", "Labor Law"],
    "practicing_court": ["District Court", "Supreme Court"],
    "lawyer_location": "Cityscape",
    "languages_known": ["English", "Telugu"],
    "experience_in_years": 8,
    "endorsements": ["Entity345"],
    "cases_involved": ["Case678", "Case901"],
    "lawyer_type": ["Advocate", "Mediator"],
    "additional_ids": ["AIBE345", "OS678", "ST901", "StateName"]
  },
  {
    "lawyer_name": "Vikram Patel",
    "vidhik_id": "V567890",
    "lawyer_password": "vikram567",
    "bar_council_no": "BCN567",
    "email": "vikram.patel@example.com",
    "photo_url": "https://example.com/vikrampatel.jpg",
    "phone_no": "8765432109",
    "aadhar_no": "876543210987",
    "gender": "Male",
    "avg_price_range_per_hearing": [150, 320],
    "no_of_past_cases_fought": 30,
    "no_of_past_cases_won": 20,
    "rating": 4,
    "speciality": ["Corporate Law", "Intellectual Property"],
    "practicing_court": ["High Court", "District Court"],
    "lawyer_location": "Metroville",
    "languages_known": ["English", "Gujarati"],
    "experience_in_years": 11,
    "endorsements": ["Entity567"],
    "cases_involved": ["Case234", "Case567"],
    "lawyer_type": ["Advocate", "Legal Advisor"],
    "additional_ids": ["AIBE567", "OS890", "ST123", "StateName"]
  },
  {
    "lawyer_name": "Sneha Bhatia",
    "vidhik_id": "V789012",
    "lawyer_password": "sneha789",
    "bar_council_no": "BCN789",
    "email": "sneha.bhatia@example.com",
    "photo_url": "https://example.com/snehabhatia.jpg",
    "phone_no": "7654321098",
    "aadhar_no": "765432109876",
    "gender": "Female",
    "avg_price_range_per_hearing": [120, 300],
    "no_of_past_cases_fought": 25,
    "no_of_past_cases_won": 15,
    "rating": 4,
    "speciality": ["Criminal Defense", "Family Law"],
    "practicing_court": ["City Court", "District Court"],
    "lawyer_location": "Suburbia",
    "languages_known": ["English", "Hindi"],
    "experience_in_years": 15,
    "endorsements": ["Entity789"],
    "cases_involved": ["Case123", "Case456"],
    "lawyer_type": ["Advocate", "Mediator"],
    "additional_ids": ["AIBE789", "OS012", "ST345", "StateName"]
  },
  {
    "lawyer_name": "Harish Singh",
    "vidhik_id": "V345678",
    "lawyer_password": "harish345",
    "bar_council_no": "BCN345",
    "email": "harish.singh@example.com",
    "photo_url": "https://example.com/harishsingh.jpg",
    "phone_no": "6543210987",
    "aadhar_no": "654321098765",
    "gender": "Male",
    "avg_price_range_per_hearing": [180, 400],
    "no_of_past_cases_fought": 28,
    "no_of_past_cases_won": 18,
    "rating": 4,
    "speciality": ["Real Estate Law", "Immigration Law"],
    "practicing_court": ["High Court", "City Court"],
    "lawyer_location": "Villageton",
    "languages_known": ["English", "Hindi"],
    "experience_in_years": 10,
    "endorsements": ["Entity345"],
    "cases_involved": ["Case567", "Case890"],
    "lawyer_type": ["Solicitor"],
    "additional_ids": ["AIBE345", "OS678", "ST901", "StateName"]
  },
  {
    "lawyer_name": "Smita Menon",
    "vidhik_id": "V567890",
    "lawyer_password": "smita567",
    "bar_council_no": "BCN567",
    "email": "smita.menon@example.com",
    "photo_url": "https://example.com/smitamenon.jpg",
    "phone_no": "6543210987",
    "aadhar_no": "654321098765",
    "gender": "Female",
    "avg_price_range_per_hearing": [150, 320],
    "no_of_past_cases_fought": 30,
    "no_of_past_cases_won": 20,
    "rating": 4,
    "speciality": ["Criminal", "Tax Law"],
    "practicing_court": ["Supreme Court", "District Court"],
    "lawyer_location": "Cityville",
    "languages_known": ["English", "Hindi"],
    "experience_in_years": 11,
    "endorsements": ["Entity567"],
    "cases_involved": ["Case890", "Case123"],
    "lawyer_type": ["Advocate", "Consultant"],
    "additional_ids": ["AIBE567", "OS890", "ST123", "StateName"]
  },
  {
    "lawyer_name": "Kunal Trivedi",
    "vidhik_id": "V123456",
    "lawyer_password": "kunal123",
    "bar_council_no": "BCN123",
    "email": "kunal.trivedi@example.com",
    "photo_url": "https://example.com/kunaltrivedi.jpg",
    "phone_no": "1234567890",
    "aadhar_no": "123456789012",
    "gender": "Male",
    "avg_price_range_per_hearing": [130, 300],
    "no_of_past_cases_fought": 40,
    "no_of_past_cases_won": 25,
    "rating": 4,
    "speciality": ["Civil Law", "Property Law"],
    "practicing_court": ["District Court", "High Court"],
    "lawyer_location": "Towntown",
    "languages_known": ["English", "Gujarati"],
    "experience_in_years": 9,
    "endorsements": ["Entity123"],
    "cases_involved": ["Case123", "Case456"],
    "lawyer_type": ["Advocate", "Legal Advisor"],
    "additional_ids": ["AIBE123", "OS456", "ST789", "StateName"]
  }
];

export const arbitrators = [
  {
    "arbitrator_name": "Amit Sharma",
    "vidhik_id": "V123456",
    "arbitrator_id": "A123456",
    "arbitrator_password": "amit123",
    "email": "amit.sharma@example.com",
    "photo_url": "https://images.app.goo.gl/GFHRkXec7FBceS6P9",
    "phone_no": "1234567890",
    "gender": "Male",
    "experience_in_years": 10,
    "profession": "Lawyer",
    "endorsements": ["Entity123"],
    "cases_involved": ["Case123", "Case456"]
  },
  {
    "arbitrator_name": "Priya Verma",
    "arbitrator_id": "A654321",
    "vidhik_id": "V654321",
    "arbitrator_password": "priya456",
    "email": "priya.verma@example.com",
    "photo_url": "https://images.app.goo.gl/RxgGPFysUwAawqrJ6",
    "phone_no": "9876543210",
    "gender": "Female",
    "experience_in_years": 8,
    "profession": "Retired Judge",
    "endorsements": ["Entity456"],
    "cases_involved": ["Case789", "Case012"]
  },
  {
    "arbitrator_name": "Rahul Kapoor",
    "arbitrator_id": "A789012",
    "vidhik_id": "V789012",
    "arbitrator_password": "rahul789",
    "email": "rahul.kapoor@example.com",
    "photo_url": "https://example.com/rahulkapoor.jpg",
    "phone_no": "8765432109",
    "gender": "Male",
    "experience_in_years": 12,
    "profession": "Mediator",
    "endorsements": ["Entity789"],
    "cases_involved": ["Case345", "Case678"]
  },
  {
    "arbitrator_name": "Neha Gupta",
    "arbitrator_id": "A345678",
    "vidhik_id": "V345678",
    "arbitrator_password": "neha345",
    "email": "neha.gupta@example.com",
    "photo_url": "https://example.com/neha-gupta.jpg",
    "phone_no": "7654321098",
    "gender": "Female",
    "experience_in_years": 15,
    "profession": "Retired Professor",
    "endorsements": ["Entity345"],
    "cases_involved": ["Case234", "Case567"]
  },
  {
    "arbitrator_name": "Ankit Malhotra",
    "arbitrator_id": "A567890",
    "vidhik_id": "V567890",
    "arbitrator_password": "ankit567",
    "email": "ankit.malhotra@example.com",
    "photo_url": "https://example.com/ankitmalhotra.jpg",
    "phone_no": "6543210987",
    "gender": "Male",
    "experience_in_years": 10,
    "profession": "Lawyer",
    "endorsements": ["Entity567"],
    "cases_involved": ["Case890", "Case123"]
  },
  {
    "arbitrator_name": "Pooja Desai",
    "arbitrator_id": "A234567",
    "vidhik_id": "V234567",
    "arbitrator_password": "pooja234",
    "email": "pooja.desai@example.com",
    "photo_url": "https://example.com/poojadesai.jpg",
    "phone_no": "9876543210",
    "gender": "Female",
    "experience_in_years": 11,
    "profession": "Mediator",
    "endorsements": ["Entity234"],
    "cases_involved": ["Case678", "Case901"]
  },
  {
    "arbitrator_name": "Rajeev Kapoor",
    "arbitrator_id": "A678901",
    "vidhik_id": "V678901",
    "arbitrator_password": "rajeev678",
    "email": "rajeev.kapoor@example.com",
    "photo_url": "https://example.com/rajeevkapoor.jpg",
    "phone_no": "8765432109",
    "gender": "Male",
    "experience_in_years": 13,
    "profession": "Retired Judge",
    "endorsements": ["Entity678"],
    "cases_involved": ["Case234", "Case567"]
  },
  {
    "arbitrator_name": "Deepika Shah",
    "arbitrator_id": "A890123",
    "vidhik_id": "V890123",
    "arbitrator_password": "deepika890",
    "email": "deepika.shah@example.com",
    "photo_url": "https://example.com/deepikashah.jpg",
    "phone_no": "7654321098",
    "gender": "Female",
    "experience_in_years": 12,
    "profession": "Mediator",
    "endorsements": ["Entity890"],
    "cases_involved": ["Case123", "Case456"]
  },
  {
    "arbitrator_name": "Sanjay Mehta",
    "arbitrator_id": "A012345",
    "vidhik_id": "V012345",
    "arbitrator_password": "sanjay012",
    "email": "sanjay.mehta@example.com",
    "photo_url": "https://example.com/sanjaymehta.jpg",
    "phone_no": "6543210987",
    "gender": "Male",
    "experience_in_years": 10,
    "profession": "Lawyer",
    "endorsements": ["Entity012"],
    "cases_involved": ["Case567", "Case890"]
  },
  {
    "arbitrator_name": "Shalini Reddy",
    "arbitrator_id": "A345678",
    "vidhik_id": "V345678",
    "arbitrator_password": "shalini345",
    "email": "shalini.reddy@example.com",
    "photo_url": "https://example.com/shalinireddy.jpg",
    "phone_no": "9876543210",
    "gender": "Female",
    "experience_in_years": 8,
    "profession": "Retired Judge",
    "endorsements": ["Entity345"],
    "cases_involved": ["Case678", "Case901"]
  },
  {
    "arbitrator_name": "Vikram Patel",
    "arbitrator_id": "A567890",
    "vidhik_id": "V567890",
    "arbitrator_password": "vikram567",
    "email": "vikram.patel@example.com",
    "photo_url": "https://example.com/vikrampatel.jpg",
    "phone_no": "8765432109",
    "gender": "Male",
    "experience_in_years": 11,
    "profession": "Mediator",
    "endorsements": ["Entity567"],
    "cases_involved": ["Case234", "Case567"]
  }
];
