// Local Database

export const lawyers = [
   {
     "lawyer_name": "John Doe",
     "vidhik_id": "V123456",
     "lawyer_password": "john123",
     "bar_council_no": "BCN123",
     "email": "john.doe@example.com",
     "photo_url": "https://images.app.goo.gl/GFHRkXec7FBceS6P9",
     "phone_no": "1234567890",
     "aadhar_no": "123456789012",
     "gender": "Male",
     "avg_price_range_per_hearing": [100, 300],
     "no_of_past_cases_fought": 50,
     "no_of_past_cases_won": 30,
     "rating": 4.5,
     "speciality": ["Criminal Defense", "Family Law"],
     "practicing_court": ["Supreme Court", "High Court"],
     "lawyer_location": "Cityville",
     "languages_known": ["English", "Spanish"],
     "experience_in_years": 10,
     "endorsements": ["Entity123"],
     "cases_involved": ["Case123", "Case456"],
     "lawyer_type": ["Advocate"],
     "additional_ids": ["AIBE123", "OS456", "ST789", "StateName"]
   },
   {
     "lawyer_name": "Jane Smith",
     "vidhik_id": "V654321",
     "lawyer_password": "jane456",
     "bar_council_no": "BCN456",
     "email": "jane.smith@example.com",
     "photo_url": "https://images.app.goo.gl/RxgGPFysUwAawqrJ6",
     "phone_no": "9876543210",
     "aadhar_no": "987654321098",
     "gender": "Female",
     "avg_price_range_per_hearing": [200, 400],
     "no_of_past_cases_fought": 40,
     "no_of_past_cases_won": 25,
     "rating": 4.2,
     "speciality": ["Corporate Law", "Intellectual Property"],
     "practicing_court": ["District Court", "Family Court"],
     "lawyer_location": "Towntown",
     "languages_known": ["English", "French"],
     "experience_in_years": 8,
     "endorsements": ["Entity456"],
     "cases_involved": ["Case789", "Case012"],
     "lawyer_type": ["Advocate", "Consultant"],
     "additional_ids": ["AIBE456", "OS789", "ST012", "StateName"]
   },
   {
     "lawyer_name": "Robert Johnson",
     "vidhik_id": "V789012",
     "lawyer_password": "robert789",
     "bar_council_no": "BCN789",
     "email": "robert.johnson@example.com",
     "photo_url": "https://example.com/robertjohnson.jpg",
     "phone_no": "8765432109",
     "aadhar_no": "876543210987",
     "gender": "Male",
     "avg_price_range_per_hearing": [150, 350],
     "no_of_past_cases_fought": 35,
     "no_of_past_cases_won": 20,
     "rating": 4.0,
     "speciality": ["Real Estate Law", "Immigration Law"],
     "practicing_court": ["High Court", "City Court"],
     "lawyer_location": "Villageton",
     "languages_known": ["English", "Mandarin"],
     "experience_in_years": 12,
     "endorsements": ["Entity789"],
     "cases_involved": ["Case345", "Case678"],
     "lawyer_type": ["Solicitor"],
     "additional_ids": ["AIBE789", "OS012", "ST345", "StateName"]
   },
   {
     "lawyer_name": "Emily Davis",
     "vidhik_id": "V345678",
     "lawyer_password": "emily345",
     "bar_council_no": "BCN345",
     "email": "emily.davis@example.com",
     "photo_url": "https://example.com/emilydavis.jpg",
     "phone_no": "7654321098",
     "aadhar_no": "765432109876",
     "gender": "Female",
     "avg_price_range_per_hearing": [120, 300],
     "no_of_past_cases_fought": 25,
     "no_of_past_cases_won": 15,
     "rating": 4.8,
     "speciality": ["Family Law", "Labor Law"],
     "practicing_court": ["City Court", "District Court"],
     "lawyer_location": "Suburbia",
     "languages_known": ["English", "German"],
     "experience_in_years": 15,
     "endorsements": ["Entity345"],
     "cases_involved": ["Case234", "Case567"],
     "lawyer_type": ["Advocate", "Mediator"],
     "additional_ids": ["AIBE345", "OS678", "ST901", "StateName"]
   },
   {
     "lawyer_name": "Michael Brown",
     "vidhik_id": "V567890",
     "lawyer_password": "michael567",
     "bar_council_no": "BCN567",
     "email": "michael.brown@example.com",
     "photo_url": "https://example.com/michaelbrown.jpg",
     "phone_no": "6543210987",
     "aadhar_no": "654321098765",
     "gender": "Male",
     "avg_price_range_per_hearing": [180, 400],
     "no_of_past_cases_fought": 28,
     "no_of_past_cases_won": 18,
     "rating": 4.3,
     "speciality": ["Criminal", "Tax Law"],
     "practicing_court": ["Supreme Court", "County Court"],
     "lawyer_location": "Townsville",
     "languages_known": ["English", "Spanish"],
     "experience_in_years": 10,
     "endorsements": ["Entity567"],
     "cases_involved": ["Case890", "Case123"],
     "lawyer_type": ["Advocate", "Consultant"],
     "additional_ids": ["AIBE567", "OS890", "ST123", "StateName"]
   }
 ];




 export const arbitrators = [
  {
    "arbitrator_name": "John Doe",
    "arbitrator_id": "A123456",
    "arbitrator_password": "john123",
    "email": "john.doe@example.com",
    "photo_url": "https://images.app.goo.gl/GFHRkXec7FBceS6P9",
    "phone_no": "1234567890",
    "gender": "Male",
    "experience_in_years": 10,
    "profession": "Lawyer",
    "endorsements": ["Entity123"],
    "cases_involved": ["Case123", "Case456"]
  },
  {
    "arbitrator_name": "Jane Smith",
    "arbitrator_id": "A654321",
    "arbitrator_password": "jane456",
    "email": "jane.smith@example.com",
    "photo_url": "https://images.app.goo.gl/RxgGPFysUwAawqrJ6",
    "phone_no": "9876543210",
    "gender": "Female",
    "experience_in_years": 8,
    "profession": "Retired Judge",
    "endorsements": ["Entity456"],
    "cases_involved": ["Case789", "Case012"]
  },
  {
    "arbitrator_name": "Robert Johnson",
    "arbitrator_id": "A789012",
    "arbitrator_password": "robert789",
    "email": "robert.johnson@example.com",
    "photo_url": "https://example.com/robertjohnson.jpg",
    "phone_no": "8765432109",
    "gender": "Male",
    "experience_in_years": 12,
    "profession": "Mediator",
    "endorsements": ["Entity789"],
    "cases_involved": ["Case345", "Case678"]
  },
  {
    "arbitrator_name": "Emily Davis",
    "arbitrator_id": "A345678",
    "arbitrator_password": "emily345",
    "email": "emily.davis@example.com",
    "photo_url": "https://example.com/emilydavis.jpg",
    "phone_no": "7654321098",
    "gender": "Female",
    "experience_in_years": 15,
    "profession": "Retired Professor",
    "endorsements": ["Entity345"],
    "cases_involved": ["Case234", "Case567"]
  },
  {
    "arbitrator_name": "Michael Brown",
    "arbitrator_id": "A567890",
    "arbitrator_password": "michael567",
    "email": "michael.brown@example.com",
    "photo_url": "https://example.com/michaelbrown.jpg",
    "phone_no": "6543210987",
    "gender": "Male",
    "experience_in_years": 10,
    "profession": "Lawyer",
    "endorsements": ["Entity567"],
    "cases_involved": ["Case890", "Case123"]
  }
];

 